version: '3'

services:
  mongodb:
    container_name: nxtix-mongo
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ADMIN}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ADMIN_PSWD}
      MONGO_INITDB_DATABASE: admin
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
