version: '3'

services:
  postgres:
    container_name: nxtix-postgres
    image: postgres:15.1
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}

    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./init-dev-db.sh:/docker-entrypoint-initdb.d/init-dev-db.sh
