#!/bin/bash

set -e

export PGPASSWORD="$POSTGRES_PASSWORD"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" -w --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER "${DATABASE_USER}" WITH PASSWORD '${DATABASE_PASSWORD}';
    CREATE DATABASE "user";
    CREATE DATABASE "product";
    CREATE DATABASE "order";
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" -w --dbname "user" <<-EOSQL
  CREATE TABLE "user" (
    id        integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username  varchar(40) NOT NULL CHECK (username <> '') UNIQUE,
    password  varchar(40) NOT NULL CHECK (password <> '')
  );
  CREATE TABLE "profile" (
    id        integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "userId"    integer UNIQUE,
    name      varchar(80),
    age       integer CHECK (age > 0)
  );
  GRANT ALL PRIVILEGES ON TABLE "user", "profile" TO ${DATABASE_USER};
EOSQL
